"""empty message

Revision ID: 9624b200e4b2
Revises: 
Create Date: 2024-04-12 22:31:20.845556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9624b200e4b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Directors',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('director_name', sa.Text(), nullable=True),
    sa.Column('director_description', sa.Text(), nullable=True),
    sa.Column('director_picture', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('director_id')
    )
    op.create_table('Films',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('film_name', sa.Text(), nullable=True),
    sa.Column('film_length', sa.Integer(), nullable=True),
    sa.Column('film_rating', sa.Integer(), nullable=True),
    sa.Column('film_year', sa.Integer(), nullable=True),
    sa.Column('film_genre', sa.Text(), nullable=True),
    sa.Column('film_director', sa.Integer(), nullable=True),
    sa.Column('film_actor', sa.Text(), nullable=True),
    sa.Column('film_trailer', sa.Text(), nullable=True),
    sa.Column('film_foto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['film_director'], ['Directors.director_id'], ),
    sa.PrimaryKeyConstraint('film_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Films')
    op.drop_table('Directors')
    # ### end Alembic commands ###
