"""empty message

Revision ID: 997565f1ca54
Revises: 9624b200e4b2
Create Date: 2024-04-14 21:17:48.040474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997565f1ca54'
down_revision = '9624b200e4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('film_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.drop_column('film_description')

    # ### end Alembic commands ###
