"""empty message

Revision ID: ffac31a74457
Revises: 8a1ef81722eb
Create Date: 2024-04-15 18:51:45.850824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffac31a74457'
down_revision = '8a1ef81722eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Directors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_date', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Directors', schema=None) as batch_op:
        batch_op.drop_column('director_date')

    # ### end Alembic commands ###
